#### Checking the generalizd variance code chunk

In [1]:
import pickle
import numpy as np
from scipy.linalg import null_space

In [2]:
# Load matrix from file
with open('matrix_mittelfranken.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Q matrix which we got from adjacencies:")
print(Q)

Q matrix which we got from adjacencies:
[[ 1 -1  0  0  0  0  0  0  0  0  0  0]
 [-1  5  0  0  0 -1  0 -1  0 -1  0 -1]
 [ 0  0  5 -1  0 -1 -1 -1 -1  0  0  0]
 [ 0  0 -1  4 -1 -1  0  0 -1  0  0  0]
 [ 0  0  0 -1  3 -1  0  0 -1  0  0  0]
 [ 0 -1 -1 -1 -1  7  0 -1 -1 -1  0  0]
 [ 0  0 -1  0  0  0  3  0 -1 -1  0  0]
 [ 0 -1 -1  0  0 -1  0  3  0  0  0  0]
 [ 0  0 -1 -1 -1 -1 -1  0  7 -1 -1  0]
 [ 0 -1  0  0  0 -1 -1  0 -1  6 -1 -1]
 [ 0  0  0  0  0  0  0  0 -1 -1  2  0]
 [ 0 -1  0  0  0  0  0  0  0 -1  0  2]]
